### ISSUE TITLE
sth.js is not in .lib folder

### ISSUE THREAD

**Issue by robbyxp1** [8bitkick/PlayUEF#4]
Hi,

Thanks for the program.  I've just decided to recreate my youth by buying a BBC micro (arriving friday).  Just trying this out as stage 1 of getting a method of sending code into it.

sth.js is in the test folder not the lib folder, so test.html fails.

Thanks

**Comment by 8bitkick** [comment]
Hey great! I will fix, thanks...

For immediate use online take a look at - http://www.8bitkick.cc/playuef---bbc-micro.html

(Test.html basically generates a massive list of URLs which are already available from the page linked above... you can use this locally, but as you will be linking to online UEFs probably easier to use the one I made already)

**Comment by robbyxp1** [comment]
Yes, i saw you updated that. ;-)

**Comment by 8bitkick** [comment]
Running test.html from within the test folder works OK. Removed duplicate test.html from root
