### ISSUE TITLE
300 baud support Chunk &0113 

### ISSUE THREAD

**Issue by PeterBBCUser** [8bitkick/PlayUEF#6]
It would appear from some testing that PlayUEF and looking in the code does not support 300 baud  Chunk &0113 - change of baud rate.
The reason I ask is that Doctor Who and the mines of Terror used baud rate change for its copy protection and have no way of testing if my UEF I have made works on a real pc, all emulators also just assume everything is 1200 baud even if its not, even MaxDuino has no 300 baud support.

**Comment by 8bitkick** [comment]
Hi @PeterBBCUser take a look at https://github.com/8bitkick/PlayUEF/blob/c53feee72f06232bc19cccf6d19efbf3d67feb78/uef2wave.js#L257 you can see that 300 baud is implemented in the dev version to support Atom. So the question is for your 300 baud whether you expect the number of wavelets x4 (as per the standard BBC Micro 300 baud) or the base frequency to drop to 300Hz
